name: Centralized Clone Workflow

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository with configuration
        uses: actions/checkout@v3

      - name: Determine target repository based on source repository
        id: determine_target
        run: |
          source_repo="${{ github.repository }}"
          target_repo=$(jq -r --arg src "$source_repo" '.[$src]' clone/repo-mappings.json)

          if [ -z "$target_repo" ]; then
            echo "No target repository found for $source_repo"
            exit 1
          fi
          echo "TARGET_REPO=${target_repo}"
          echo "TARGET_REPO=${target_repo}" >> $GITHUB_ENV


